# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  train_path: data/wiki/node_ids/train_ids.pkl
  test_path: data/wiki/node_ids/test_ids.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: new_naive
  method: previous_week
  data_path: ./data/wiki/wiki.hdf5
  series_len: 1827
  backcast_length: 112
  forecast_length: 28
  test_lengths: [7, 14, 21, 28]
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 4
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
    parameter_groups:
      - - - project_in
        - {}
      - - - ^decoder.layers.0
        - {}
      - - - ^decoder.layers.1
        - {}
      - - - ^decoder.layers.2
        - {}
      - - - ^fc
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
    num_steps_per_epoch: 10000
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 10
      validation_metric: "-smape_28"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
